app/models.py
from datetime import datetime
from flask_login import UserMixin

from werkzeug.security import generate_password_hash,check_password_hash

from . import db,login_manager

@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

class User(UserMixin,db.Model):
    """This will define all behaviours within the user class

    Args:
        UserMixin ([type]): [description]
        db ([model]): [This is to connect the user to the database]

    Raises:
        AttributeError: [This will be the case when one tries to access the password]

    Returns:
        [dict]: [This is what will be returned when one views the user class and its contents]
    """
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique=True,index=True)
    pass_secure = db.Column(db.String(255))
    pitches = db.relationship('Pitch',backref = 'pitche',lazy = "dynamic")
    comments = db.relationship('Comment',backref = 'commenter',lazy="dynamic")
    profile_pic_path = db.Column(db.String(255))

    @property
    def password(self):
        """This will prevent reading of the password
        """
        raise AttributeError('You cannot read the password')

    @password.setter
    def password(self,password):
        """This will turn the password into hashes

        Args:
            password ([string]): [This is the input password]
        """
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        """This will check the set series of hashes and the hashes from the inputted password to see if they match

        Args:
            password ([string]): [This is the input password]
        """
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'


class Pitch(db.Model):
    """This will define all behaviours of the comments

    Args:
        UserMixin ([type]): [description]
        db ([Model]): [This will connect all the comments to the database]
    """
    __tablename__ = 'pitches'

    pitch_id = db.Column(db.Integer,primary_key=True)
    pitch_category = db.Column(db.String(255))
    pitch = db.Column(db.String(255))
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    comments = db.relationship('Comment',backref = 'commente',lazy = "dynamic")

    def __repr__(self):
        return f'Pitch {self.pitch}'

class Comment(db.Model):
    """This is the comment class and it will define all the behaviours of the comments

    Args:
        db ([Model]): [This will connect all the comments to the database]
    """

    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key=True)
    comment = db.Column(db.String(255))
    pitch_id = db.Column(db.Integer,db.ForeignKey('pitches.pitch_id'))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    upvote = db.Column(db.Integer)

    def __repr__(self):
        return f'Comment {self.comment}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,RadioField,TextAreaField
from wtforms.validators import Required

class PitchForm(FlaskForm):
    """This class will define the form to create a pitch

    Args:
        FlaskForm ([type]): [description]
    """
    pitch = StringField('Enter your pitch',validators=[Required()])
    pitch_category = RadioField('Enter the category of the pitch',validators=[Required()],choices=[('interview'),('promotion'),('Pickup lines'),('Comedy lines')])
    submit = SubmitField('Pitch')

class CommentForm(FlaskForm):
    """This will define all features of a comment form

    Args:
        FlaskForm ([type]): [description]
    """
    comment = TextAreaField('Comment here...',validators=[Required()])
    vote = RadioField('Upvote or downvote',validators=[Required()],choices=[(1),(-1)])
    submit = SubmitField('Comment')

app/__init__.py
from flask import Flask,render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

from config import config_options

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def four_Ow_four(error):
    '''
    Function to render the 404 error page
    '''
    return render_template('404.html'),404

def create_app(config_name):
    """This is the app factory function
    """
    app = Flask(__name__)

    #setting up the configurations
    app.config.from_object(config_options[config_name])

    #initializing the extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    configure_uploads(app,photos)

    #registering blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/authentication')

    app.register_error_handler(404,four_Ow_four)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

app/main/views.py
from flask import render_template,abort,flash,redirect,request
from flask.helpers import url_for
from flask_login import login_required,current_user

from app.models import Comment, Pitch, User, db
from . import main
from .forms import PitchForm,CommentForm
from .. import photos

@main.route('/')
def index():
    title = 'PITCH ARENA'
    return render_template('index.html',title = title)

@main.route('/profile/<username>')
@login_required
def profile(username):
    user = User.query.filter_by(username = username).first()
    pitch_list = []
    pitches = Pitch.query.all()
    for pitch in pitches:
        if pitch.pitche.username == username:
            pitch_list.append(pitch)

    if user is None:
        abort(404)
    return render_template('profile/profile.html',user = user,pitches = pitch_list)

@main.route('/create',methods = ["GET","POST"])
@login_required
def create_pitch():
    """This will create the pitch according to the category
    """
    pitch_form = PitchForm()
    if pitch_form.validate_on_submit():
        pitch = Pitch(pitch = pitch_form.pitch.data,pitch_category = pitch_form.pitch_category.data,user_id = current_user.id)
        db.session.add(pitch)
        db.session.commit()
        return redirect(url_for('main.show_pitch'))

    return render_template('pitch/create_pitch.html',pitch = pitch_form)

@main.route('/pitch')
def show_pitch():
    """This function will display all the pitches
    """
    interview_pitches = Pitch.query.filter_by(pitch_category = 'interview').all()
    promotion_pitches = Pitch.query.filter_by(pitch_category = 'promotion').all()
    pickup_lines = Pitch.query.filter_by(pitch_category = 'Pickup lines').all()
    comedic_quips = Pitch.query.filter_by(pitch_category = 'Comedy lines').all()

    return render_template('pitch/pitch.html',interview_pitches = interview_pitches,promotion_pitches = promotion_pitches,pickup_lines = pickup_lines,comedic_quips = comedic_quips)

@main.route('/comment/<pitch_id>',methods=["GET","POST"])
@login_required
def comment(pitch_id):
    """This will add a comment
    """
    pitches = Pitch.query.all()
    comment_form = CommentForm()
    comments = Comment.query.all()
    if comment_form.validate_on_submit():
        comment = Comment(comment = comment_form.comment.data, upvote = comment_form.vote.data,pitch_id = pitch_id,user_id = current_user.id)
        db.session.add(comment)
        db.session.commit()

        return redirect(url_for('main.comment',pitch_id = pitch_id))
    return render_template('comment.html',form = comment_form,comments = comments,pitches = pitches,pitch_id = pitch_id)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',username=uname))

app/views.py
from flask import render_template
from . import app

@app.route('/')
def index():
    return render_template('index.html')

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap,family=Roboto:wght@300&display=swap" rel="stylesheet">
    <!-- <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet"> -->
    <link rel="stylesheet" href="{{ url_for('static',filename='styles.css')}}">
    <link rel="icon" href="{{ url_for('static',filename='Logo.png')}}">
    <title>{{ title }}</title>
</head>

<body>
    {% block navbar %} {% include 'navbar.html' %} {% endblock %} {% block content%}{% endblock %}{% include 'footer.html'%}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

app/templates/comment.html
{% extends 'base.html' %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-4" style="border:solid black 1px; padding: 10px;height: 60vh;margin-top:10px">
            <form class="container-fluid" method="POST">
                {{ form.hidden_tag()}}
                <div class="mb-3">
                    {{ form.comment.label(class="form-label")}}{{ form.comment(class="form-control")}}
                </div>
                <div class="mb-3">
                    <button class="btn btn-outline-secondary">{{ form.vote }}</button>
                </div>
                <div class="mb-3">
                    {{ form.submit(class="btn btn-success")}}
                </div>
            </form>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-5">
            {% for comment in comments %}
            <div class="card" style="margin: 10px;">
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <p>{{ comment.comment }}</p>
                        <footer class="blockquote-footer">{{ comment.commenter.username }}</footer>
                    </blockquote>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/footer.html
<div style="text-align: center;" class="footer">
    <p>&#169 2021 Ken Mbira</p>
</div>

app/templates/index.html
{% extends 'base.html' %} {% block content %}
<div class="card">
    <div class="row g-0">
        <div class="col-md-8">
            <div class="card-body" id="intro">
                <p class="card-text">Many times you have only that one minute to make a point and it's quite stressful to figure out what to say, you know what, why don't you let us worry about that.</p>
                <p class="card-text"><small style="font-size: 3vmin;" class="text-muted">Someone who only had a minute to say this.</small></p>
            </div>
        </div>
        <div class="col-md-4">
            <img src="{{ url_for('static',filename='microphone.jpg')}}" class="img-fluid" alt="image of a microphone">
        </div>
    </div>
</div>
<div class="call-to-actions" style="text-align: center;">
    <div>
        <a class="btn" id="intro" style="background-color: #3B3355;" href="{{ url_for('main.create_pitch')}}">Create a pitch</a>
    </div>
    <div>
        <a class="btn" id="intro" style="background-color: #3B3355;" href="{{ url_for('main.show_pitch')}}">View pitches</a>
    </div>
</div>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #5D5D81;">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><img src="{{ url_for('static',filename='Logo.png')}}" style="max-width: 40px;"></a>
        <div class="navbar-right">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('main.index')}}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Interview pitch</a></li>
                            <li><a class="dropdown-item" href="#">Promotion pitch</a></li>
                            <li><a class="dropdown-item" href="#">Pickup lines</a></li>
                            <li><a class="dropdown-item" href="#">Comedy lines</a></li>
                        </ul>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">{{ current_user.username}}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.profile',username = current_user.username)}}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout')}}">Signout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login')}}">Log in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register')}}">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>

app/templates/pitch.html
{% extends 'base.html' %} {% block content %} {% for message in get_flashed_messages()%}
<div class="alert alert-success" role="alert">
    {{ message }}
</div>
{% endfor %}
<div class="container" style="border:solid black 1px; padding: 10px; margin-top:20px;">
    <form class="container-fluid" method="POST">
        {{ pitch.hidden_tag()}}
        <div class="mb-3">
            {{ pitch.pitch.label(class="form-label")}}{{ pitch.pitch(class="form-control")}}
        </div>
        <div class="mb-3">
            <p>Choose the pitch category</p>
            {{ pitch.pitch_category(class="list-group-flush")}}
        </div>
        <div class="mb-3">
            {{pitch.submit(class="btn btn-success")}}
        </div>

    </form>
</div>
{% endblock%}

app/templates/pitch/create_pitch.html
{% extends 'base.html' %} {% block content %} {% for message in get_flashed_messages()%}
<div class="alert alert-success" role="alert">
    {{ message }}
</div>
{% endfor %}
<div class="container" style="border:solid black 1px; padding: 10px; margin-top:20px;">
    <form class="container-fluid" method="POST">
        {{ pitch.hidden_tag()}}
        <div class="mb-3">
            {{ pitch.pitch.label(class="form-label")}}{{ pitch.pitch(class="form-control")}}
        </div>
        <div class="mb-3">
            <p>Choose the pitch category</p>
            {{ pitch.pitch_category(class="list-group-flush")}}
        </div>
        <div class="mb-3">
            {{pitch.submit(class="btn btn-success")}}
        </div>

    </form>
</div>
{% endblock%}

app/templates/pitch/pitch.html
{% extends 'base.html' %} {% block content %}
<div class="accordion accordion-flush" id="accordionFlushExample">
    <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
          Interview Pitch
        </button>
        </h2>
        <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
            {% if interview_pitches %} {% for item in interview_pitches %}
            <div class="card">
                <div class="card-body">
                    <p class="card-text">{{ item.pitch }}</p>
                    <p class="card-text"><small class="text-muted">{{ item.pitche.username }}</small></p>
                    <p class="card-text"><small class="text-muted">{{ item.posted.strftime('%Y-%m-%d') }}</small></p>
                    <a href="{{url_for('main.comment',pitch_id = item.pitch_id)}}" class="btn btn-secondary">Comment</a>
                </div>
            </div>
            {% endfor %} {% else %}
            <div>
                <p>There are no Interview pitches yet, perhaps you would like to <span><a href="{{ url_for('main.create_pitch')}}">add one</a></span></p>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
          Promotion pitch
        </button>
        </h2>
        <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
            {% if promotion_pitches %} {% for item in promotion_pitches %}
            <div class="card">
                <div class="card-body">
                    <p class="card-text">{{ item.pitch }}</p>
                    <p class="card-text"><small class="text-muted">{{ item.pitche.username }}</small></p>
                    <p class="card-text"><small class="text-muted">{{ item.posted.strftime('%Y-%m-%d') }}</small></p>
                    <a href="{{url_for('main.comment',pitch_id = item.pitch_id)}}" class="btn btn-secondary">Comment</a>
                </div>
            </div>
            {% endfor %} {% else %}
            <div>
                <p>There are no Promotion pitches yet, perhaps you would like to <span><a href="{{ url_for('main.create_pitch')}}">add one</a></span></p>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingThree">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
          Pickup line
        </button>
        </h2>
        <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
            {% if pickup_lines %}{% for item in pickup_lines %}
            <div class="card">
                <div class="card-body">
                    <p class="card-text">{{ item.pitch }}</p>
                    <p class="card-text"><small class="text-muted">{{ item.pitche.username }}</small></p>
                    <p class="card-text"><small class="text-muted">{{ item.posted.strftime('%Y-%m-%d') }}</small></p>
                    <a href="{{url_for('main.comment',pitch_id = item.pitch_id)}}" class="btn btn-secondary">Comment</a>
                </div>
            </div>
            {% endfor %} {% else %}
            <div>
                <p>There are no Pickup lines yet, perhaps you would like to <span><a href="{{ url_for('main.create_pitch')}}">add one</a></span></p>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingFour">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFour" aria-expanded="false" aria-controls="flush-collapseFour">
          Comedic quips
        </button>
        </h2>
        <div id="flush-collapseFour" class="accordion-collapse collapse" aria-labelledby="flush-headingFour" data-bs-parent="#accordionFlushExample">
            {% if comedic_quips %}{% for item in comedic_quips %}
            <div class="card">
                <div class="card-body">
                    <p class="card-text">{{ item.pitch }}</p>
                    <p class="card-text"><small class="text-muted">{{ item.pitche.username }}</small></p>
                    <p class="card-text"><small class="text-muted">{{ item.posted.strftime('%Y-%m-%d') }}</small></p>
                    <a href="{{url_for('main.comment',pitch_id = item.pitch_id)}}" class="btn btn-secondary">Comment</a>
                </div>
            </div>
            {% endfor %} {% else %}
            <div>
                <p>There are no Comedic quips yet, perhaps you would like to <span><a href="{{ url_for('main.create_pitch')}}">add one</a></span></p>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %} {% block content %}
<div class="container">
    <div style="text-align: center;">
        {% if user.profile_pic_path %}
        <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" width="250px"> {% else %}
        <p>No profile picture </p>
        <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">

            <input type="file" name="photo" class="form-control" required>
            <input type="submit">
        </form>
        {% endif %}
        <h3>{{ user.username }}</h3>
    </div>
    <div class="row">
        <div class="btn-group" role="group" aria-label="Basic example">
            <a class="btn btn-secondary" href="#">Interview</a>
            <a class="btn btn-secondary" href="#">Promotion Pitch</a>
            <a class="btn btn-secondary" href="#">Pickup Lines</a>
            <a class="btn btn-secondary" href="#">Comedy lines</a>
        </div>
        <div class="">
            {% for pitch in pitches %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ pitch.pitch }}</h5>
                    <a href="{{url_for('main.comment',pitch_id = pitch.pitch_id)}}" class="btn btn-outline-secondary">See Comments</a>
                    <p class="card-text"><small class="text-muted">{{ pitch.posted.strftime('%Y-%m-%d') }}</small></p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}